# Generated by Django 3.2.18 on 2023-04-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garment',
            name='style',
            field=models.CharField(max_length=100),
        ),
    ]
